name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:
  build-and-push-image:
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - name: docker.io-postgres-16.0-bookworm_2.0.1-wal-g-pg-ubuntu-20.04-amd64
            postgres-image: docker.io/postgres:16.0-bookworm
            wal-g-binary: 2.0.1-wal-g-pg-ubuntu-20.04-amd64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Dockerfile for the combination
      run: |
        cat <<EOF > Dockerfile
        FROM ${{ matrix.postgres-image }}
        
        COPY files/${{ matrix.wal-g-binary }} /usr/local/bin/wal-g
        EOF
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Lowercase repository and image name
      run: |
        echo IMAGE_REPOSITORY=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        echo IMAGE=$(echo "${{ matrix.name }}" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
    - name: Build and push the image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE }}:${{ github.run_number }}, ${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE }}:latest
        labels: ${{ steps.meta.outputs.labels }}


