name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:
  build-and-push-image:
    strategy:
      matrix:
        include:
          - postgres: 16.0-bookworm
            wal-g: 2.0.1-wal-g-pg-ubuntu-20.04-amd64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Dockerfile for the combination
      run: |
        cat <<EOF > Dockerfile
        FROM postgres:${{ matrix.postgres }}
        
        COPY files/${{ matrix.wal-g }} /usr/local/bin/wal-g
        EOF
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: lowercase-repository
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        echo IMAGE_TAG=$(echo "postgres-wal-g:${{ matrix.postgres }}-${{ matrix.wal-g }}" | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV
    - name: Build and push the image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_TAG }}
        labels: ${{ steps.meta.outputs.labels }}


